### ISSUE TITLE
0.5.0.beta2 not on rubygems

### ISSUE THREAD

**Issue by anothermh** [tiagopog/jsonapi-utils#31]
README says to use `gem 'jsonapi-utils', '0.5.0.beta2'` but beta2 is not yet released to rubygems. Only beta1 is available.

**Comment by tiagopog** [comment]
Sorry, @anothermh, it was my fault to let it go to the `README`. I still did not tag and release this new version of the gem because changes in the PR #27 will be packed along with the current changes on `master`. For now I'm going to fix the README, but `v0.5.0.beta2` might be released soon. Thanks!
