### ISSUE TITLE
Update to use jsonapi-resources 0.8.0

### ISSUE THREAD

**Issue by jayfredlund** [tiagopog/jsonapi-utils#33]
Hi @tiagopog,

Thanks for maintaining this gem.  I've forked a copy and changed the gem to use version jsonapi-resources version 0.8.0 final, which was released today.

Separately, I've removed the dependency for piped_ruby, which (it appears) you added into beta2, and is why I haven't proposed my fork back into yours.  I'm not sure why the dependency was added, and I can't find any discussion about it, but it doesn't seem to be necessary for this gem to work properly.  It also seems like requiring piped_ruby forces someone into a design decision unrelated to the use of jsonapi.

I'm happy to propose a PR with the updated version, and/or rename this issue title, but I just was hoping for some clarification on the piped_ruby dependency and why it was added as a requirement.

Thanks!

**Comment by tiagopog** [comment]
Hi @jayfredlund,

Piped Ruby brings some facilities when it comes to represent data transformation in code. See the [code snippet](https://github.com/tiagopog/jsonapi-utils/blob/master/lib/jsonapi/utils/response/formatters.rb#L60) where it's applied.

It's a really tiny gem and I was willing to use it in order to refactor some parts of the code where its use makes sense.

I'm open to different views and for now I don't see any problem on rolling back to the previous implementation (or maybe a new one) and open a topic later for farther discussions. What do you think?

I'm looking forward for your PR. Cheers!
