### ISSUE TITLE
Relax jsonapi-resources dependency

### ISSUE THREAD

**Issue by grk** [tiagopog/jsonapi-utils#93]
jsonapi-resources version is now locked to 0.9.0. 0.9.2 has been recently released, but can't be used with jsonapi-utils.

**Comment by jsmestad** [comment]
@grk I put up a patch for this in PR #88

**Comment by tiagopog** [comment]
Hi there. Firstly, sorry for the long delay on answering you guys (parenting thing here).

@jsmestad thanks for the previous PR. Unfortunately I was struggling to find some free time on the past couple of months and when I had it I got focused on the higher priority tasks for the OSS projects I'm involved. Now that things on my day-to-day basis are becoming a bit lighter, I'm planning to have some iterations on JU and close all the open (PR|issue)s.

@grk initially this dependency was relaxed, but historically JR brings a lot of breaking changes for each minor version. Thus very often people used to come up here with weird bugs which we ended up figuring out that they were due to a version mismatch between the gems. When eventually JR get to the `v1.0` and if JU is still using it as its serializer layer, then I think we should start considering decoupling the versions of the gems again.

@grk @jsmestad may you guys do an initial test with `0.9.3` and provide a PR with the version bump?

Thanks :-)

**Comment by jsmestad** [comment]
@tiagopog You can give PR #88 a try, but as I mentioned above I was unable to figure out what changes JSONAPI::Resources made internally that triggers the new `undefined method 'include_directives' for {}:Hash` error and had to roll back.
